# Generated by Django 3.0.6 on 2020-05-21 08:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_store',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='shop_image/'),
        ),
    ]
